### ISSUE TITLE
Gem can't find the dictionaries

### ISSUE THREAD

**Issue by helphop** [kupolak/textstat#28]
I am getting the following error when I try to run this gem:

Errno::ENOENT: No such file or directory @ rb_sysopen - lib/dictionaries/en_us.txt

I've checked the directories and the dictionaries are all there.

I have changed the textstat.rb file line 155 as follows:

    File.read("#{__dir__}/dictionaries/#{language}.txt").each_line do |line|
      easy_words << line.chop
    end

This fixes the problem. I'm not sure if this is working for all other users or if others are having the same issue as I am.

**Comment by jmartyniak** [comment]
I am having the same issue.  thank you for the fix.  how do we get that into the gem?  PR?

**Comment by helphop** [comment]
I'm very happy to know that I'm not the only one and that the code has helped.  I could create a pull request and submit the code. I just don't know how to do that. If you do please do so, there may be others who could benefit.

**Comment by kupolak** [comment]
@helphop @jmartyniak Thank you for your interest in this gem! I am busy lately, so sorry for my late response. I welcome your PR, you just have to fork my repository, make changes in your fork, commit and push it to your fork and create a pull request to my repository.

**Comment by kupolak** [comment]
Merged #29
